project:
  type: website
  output-dir: docs

# Meta
description-meta: "Based on the Quarto Academic Website Template adapted by Dr. Gang He"
author-meta: "Nicolas Robinson-Garcia"

website:
  title: "Nicolas Robinson-Garcia"
  image: "privatesign.png"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
      - text: Home
        href: index.qmd
      - text: Research
        menu:
          - text: Projects
            href: projects.qmd
          - text: Publications
            href: publications.qmd
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        href: teaching.qmd
      - text: Outreach
        href: outreach.qmd
      - text: Do not read
        href: posts.qmd

    right: 
      # - text: CV
      #   href: files/nsf-biosketch.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/nicolasrobinson/
      - icon: github
        href: https://github.com/elrobin
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/nrobinsongarcia.bsky.social
        target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Nicolas Robinson-Garcia](http://www.github.com/elrobin) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Adapted with ❤️ from the [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/elrobin
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/nrobinsongarcia.bsky.social
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/elrobin/elrobin.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://elrobin.github.io"

format:
  html:
    theme: simplex
    css: custom.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: fonts.html # "files/includes/_academic.qmd"

